modLoader="javafml"
loaderVersion="[33,)"
license="CC BY-NC-SA 4.0 IPL"
issueTrackerURL="http://github.com/itsmeow/QuickTeleports/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/quickteleports"
logoFile="quickteleports.png"
credits="its_meow, for programming, ideas, design, and leading"
authors="its_meow"
[[mods]]
modId="quickteleports"
version="${file.jarVersion}"
displayName="QuickTeleports"
description='''
This mod adds a quick and easy way to send tp requests with /tpa and /tpaccept'''
[[dependencies.quickteleports]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.0,)"
    ordering="NONE"
    side="SERVER" 
[[dependencies.quickteleports]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="SERVER" 
